volumes:
    cache:

services:
    velocity:
        image: ghcr.io/termermc/eagler-velocity:latest
        build:
            dockerfile: ./Dockerfile
            network: host
            context: .

        ports:
         - "25565:25565"

        volumes:
         - cache:/data/cache/
         - ./server-icon.png:/data/server-icon.png
         - ./secrets/:/data/secrets/
         - ./velocity.toml:/data/velocity.toml
         - ./plugins:/data/plugins/
